---
title: "David_Trees"
output: html_document
date: "2022-12-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("rpart", repos='http://cran.us.r-project.org') # Classification trees, rpart(formula, data=, method=,control=)
library(rpart)
```

```{r, echo = T, fig.dim=c(6,4)}
set.seed(1)
neo <- read.csv("neo.csv")
neofit <- rpart(hazardous ~ relative_velocity + absolute_magnitude + miss_distance, data=neo, method="class", control = list(maxdepth = 4) )
printcp(neofit) # display the results 
plotcp(neofit) # visualize cross-validation results 
summary(neofit) # detailed summary of splits

# plot tree 
plot(neofit, uniform=TRUE, main="Classification Tree for NEO")
text(neofit, use.n=TRUE, all=TRUE, cex=.8)

```

```{r}
post(neofit, file = "neoTree.ps", title = "Classification Tree for NEO")
```

```{r, include=T}
install.packages("caret", repos='http://cran.us.r-project.org')
library(caret)
```

```{r fancyplot}
install.packages("rpart.plot", repos='http://cran.us.r-project.org')
library(rpart.plot)
install.packages("rattle", repos='http://cran.us.r-project.org')
library(rattle)
fancyRpartPlot(neofit)
```

```{r, include=FALSE}
confusionMatrixResultDf = data.frame( Depth=numeric(0), Accuracy= numeric(0), Sensitivity=numeric(0), Specificity=numeric(0), Pos.Pred.Value=numeric(0), Neg.Pred.Value=numeric(0), Precision=numeric(0), Recall=numeric(0), F1=numeric(0), Prevalence=numeric(0), Detection.Rate=numeric(0), Detection.Prevalence=numeric(0), Balanced.Accuracy=numeric(0), row.names = NULL )
```

```{r}
install.packages("ISLR",repos='http://cran.us.r-project.org')
library(ISLR)
install.packages("tree",repos='http://cran.us.r-project.org')
library("tree")
treefit <- tree(log(miss_distance) ~ relative_velocity  + absolute_magnitude , data=neo)
summary(treefit)
```

```{r}
plot(treefit) 
text(treefit,cex=0.75)
```

