---
title: "Team1_Project2"
author: "Tyler, Anushka and David"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(ezids)
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

# Reading the dataset

```{r , echo=FALSE}
#Importing `ipums.csv` dataset
getwd()
ipums = data.frame(read.csv('ipums.csv'))

str(ipums)

#Dropping unnecessary columns: YEAR, EDUCD and EMPSTATD
library(dplyr)
ipums = select(ipums, c(2:6,8,10))

str(ipums)

#Using random sample data (as recommended) with new `ipumsdf`
#set.seed(123)
#ipumsdf = ipums[ sample(nrow(ipums),100000), ]
#ipumsdf
```


# Reformatting target variable - EMPSTAT

```{r, results='markup'}
#Reformatting target column: EMPSTAT

#Checking for unique values
unique(ipums$EMPSTAT)

#According to IPUMS, codes are the following:
# 0 = N/A
# 1 = Employed
# 2 = Unemployed
# 3 = Not in labor force

#Dropping 0 and 3 values
ipums$EMPSTAT <- replace(ipums$EMPSTAT, ipums$EMPSTAT == 0, NA)
ipums$EMPSTAT <- replace(ipums$EMPSTAT, ipums$EMPSTAT == 3, NA)

ipums <- na.omit(ipums)

#Reformatting column to:
# 0 = Unemployed
# 1 = Employed

ipums$EMPSTAT[ipums$EMPSTAT == 2] <- 0

ipums$EMPSTAT <- as.factor(ipums$EMPSTAT)
```


# EDA: EDUC
```{r, results='markup'}
#Reformatting columns: EDUC and WORKEDYR

#Checking for unique values
sort(unique(ipums$EDUC))

#According to IPUMS, codes are the following:
# 0 = No schooling
# 1 = 4th grade (Elementary-school)
# 2 = 5th, 6th, 7th or 8th grade (Middle-school)
# 3 = 9th grade
# 4 = 10th grade
# 5 = 11th grade 
# 6 = 12th grade (High-school)
# 7 = 1st year college
# 8 = 2nd year college
# 10 = 4th year college (Undergraduate)
# 11 = 5+ year college (Masters or PHD)

#Reformatting column to:
# 0 = No schooling
# 1 = 4th grade (Elementary-school)
# 2 = 5th, 6th, 7th or 8th grade (Middle-school)
# 3 = 9th grade
# 4 = 10th grade
# 5 = 11th grade 
# 6 = 12th grade (High-school)
# 7 = 1st year college
# 8 = 2nd year college
# 9 = 4th year college (Undergraduate)
# 10 = 5+ year college (Masters or PHD)

ipums$EDUC[ipums$EDUC == 10] <- 9
ipums$EDUC[ipums$EDUC == 11] <- 10

ipums$EDUC <- as.factor(ipums$EDUC)
```


```{r, results='markup'}
#EDA 

#Proportion table for EDUC
table1 <- table(ipums$EMPSTAT, ipums$EDUC)
table1

#EDUC barplot
barplot( prop.table(table1, 2),
         legend.text = TRUE,
         ylab = "Proportion employment",
         xlab = "Highest level of education attained",
         names.arg=c('No schooling','Elementary-S','Middle-S','9th','10th','11th','High-S','1st-C','2nd-C','Undergraduate','Masters'),
         args.legend = list(x = "topright",
                          legend = c("Employed", "Unemployed"),
                           inset = c(- 0.06, -0.13),
                          cex = 0.60),
         main = "Barplot of proportion `EMPSTAT` vs `EDUC`", las=2, cex.names=0.75)

```

# EDA: AGE
```{r, results='markup'}
#EDA 

#Age histogram plot by employment 
Unemployed = subset(ipums, ipums$EMPSTAT == 0)

Employed = subset(ipums, ipums$EMPSTAT == 1)

library('ggplot2')
ggplot(Unemployed, aes(AGE, ..count../sum(..count..)*100))+
  geom_histogram(col = 'black', fill ='#FF9999', bins = 20)+
  labs(title = 'Relative frequency histogram of age by Unemployed')+
  xlab('Age')+
  ylab('Frequency %')

ggplot(Employed, aes(AGE, ..count../sum(..count..)*100))+
  geom_histogram(col = 'black', fill ='#009E73', bins = 20)+
  labs(title = 'Relative frequency histogram of age by Employed')+
  xlab('Age')+
  ylab('Frequency %')
```

# EDA: MARST (Marital Status)
```{r, results='markup'}

#According to IPUMS, codes are the following:
# 1 = Married, spouse present
# 2 = Married, spouse absent
# 3 = Separated	
# 4 = Divorced
# 5 = Widowed
# 6 = Never married/single

#Reformatting to:
# 1 = Married
# 2 = Separated	
# 3 = Divorced
# 4 = Widowed
# 5 = Single

ipums$MARST[ipums$MARST == 2] <- 1
ipums$MARST[ipums$MARST == 3] <- 2
ipums$MARST[ipums$MARST == 4] <- 3
ipums$MARST[ipums$MARST == 5] <- 4
ipums$MARST[ipums$MARST == 6] <- 5

ipums$MARST = as.factor(ipums$MARST)

```


```{r, results='markup'}
#EDA 

#Proportion table for EDUC
table2 <- table(ipums$EMPSTAT, ipums$MARST)
table2

#EDUC barplot
barplot( prop.table(table2, 2),
         legend.text = TRUE,
         ylab = "Proportion employment",
         xlab = "Marital Status",
         names.arg=c('Married','Separated','Divorced','Widowed','Single'),
         args.legend = list(x = "topright",
                          legend = c("Employed", "Unemployed"),
                           inset = c(- 0.06, -0.13),
                          cex = 0.60),
         main = "Barplot of proportion `EMPSTAT` vs `MARST`", las=1, cex.names=0.85)

```


# EDA: GENDER
```{r, results='markup'}
# 1 => Male
# 2 => Female

library("dplyr")

# renaming the column
ipums = ipums %>% rename("GENDER" = "SEX")
print(colnames(ipums))

dat <- data.frame(table(ipums$GENDER,ipums$EMPSTAT))
names(dat) <- c("GENDER","EMPSTAT","Count")
# for purpose of plotting
dat["GENDER"] = c("Male","Female","Male","Female")

# plotting
ggplot(data=dat, aes(x=GENDER, y=Count)) + geom_bar(aes(fill = EMPSTAT), stat="identity")+ scale_fill_discrete(labels = c("UNEMPLOYED", "EMPLOYED")) 


```
# EDA: INDUSTRY
```{r, results='markup'}
# INDNAICS
ipums = ipums %>% mutate(INDUSTRY = 
  case_when(
    startsWith(INDNAICS,"0") ~ "Not_Applicable",
    startsWith(INDNAICS,"1") ~ "Agriculture",
    startsWith(INDNAICS,"2") ~ "Utilities",
    startsWith(INDNAICS,"3") ~ "Manufacturing",
    startsWith(INDNAICS,"4") ~ "Retail",
    startsWith(INDNAICS,"5") ~ "Finance",
    startsWith(INDNAICS,"6") ~ "Education and Health",
    startsWith(INDNAICS,"7") ~ "Hospitalioty",
    startsWith(INDNAICS,"8") ~ "Other",
    startsWith(INDNAICS,"9") ~ "Military"
  )
)

# plotting

gender_name <- c(
  `1`="Male",
  `2`="Female"
)
gender_labeller <- function(variable,value){
  return(gender_name[value])
}

ggplot(ipums, aes(INDUSTRY, ..count..)) + geom_bar(aes(fill = EMPSTAT), position = "dodge") +
facet_wrap(GENDER ~ ., labeller = gender_labeller) + theme(axis.text.x = element_text(angle = 45, hjust=1))+ scale_fill_discrete(labels = c("UNEMPLOYED", "EMPLOYED"))

```

# Downsampling
```{r, results='markup'}
set.seed(123)
ipums_employed = (ipums %>% filter(EMPSTAT==1))
ipums_not_employed = (ipums %>% filter(EMPSTAT==0))

ipums_sample_employed = ipums_employed[sample(nrow(ipums_employed),nrow(ipums_not_employed)),]
ipums_model_data= rbind(ipums_sample_employed, ipums_not_employed)
nrow(ipums_model_data)

# Let's plot our industry vs gender vs empstatus again to see the distribution after sampling
ggplot(ipums_model_data, aes(INDUSTRY, ..count..)) + geom_bar(aes(fill = EMPSTAT), position = "dodge") + facet_wrap(GENDER ~ ., labeller = gender_labeller) + theme(axis.text.x = element_text(angle = 45, hjust=1))+ scale_fill_discrete(labels = c("UNEMPLOYED", "EMPLOYED"))
```

# Splitting into train and test data

```{r, results='markup'}

ipums_model_data = ipums_model_data %>% select(GENDER, AGE, MARST, CITIZEN, INDUSTRY, EDUC, EMPSTAT)

# refactor into numeric
ipums_model_data$EMPSTAT = as.numeric(ipums_model_data$EMPSTAT)
ipums_model_data$INDUSTRY = as.numeric(unclass(as.factor(ipums_model_data$INDUSTRY)))


## 75% of the sample size
smp_size <- floor(0.75 * nrow(ipums_model_data))

## set the seed to make your partition reproducible
set.seed(123)
train_data_size <- sample(seq_len(nrow(ipums_model_data)), size = smp_size)

train <- ipums_model_data[train_data_size,]
test <- ipums_model_data[-train_data_size,]

train.labels = ipums_model_data[train_data_size,c("EMPSTAT")]
test.labels = ipums_model_data[-train_data_size,c("EMPSTAT")]

paste0("Number of employed people in training set = ", (nrow(train %>% filter(EMPSTAT==1))))
paste0("Number of unemployed people in training set = ", (nrow(train %>% filter(EMPSTAT==0))))

paste0("Number of employed people in testing set = ", (nrow(test %>% filter(EMPSTAT==1))))
paste0("Number of unemployed people in testing set = ", (nrow(test %>% filter(EMPSTAT==0))))
```

# KNN
```{r, results='markup'}
library(class)
knn.27 <- knn(train=train, test=test, cl=train.labels, k=27)
ACC.27=100 * sum(test.labels == knn.27)/NROW(test.labels)
paste0("Accuracy = ", ACC.27)
```